FROM ubuntu:latest

RUN apt-get update && \
  apt-get install -yy \
    autoconf \
    automake \
    build-essential \
    git \
    make \
    maven \
    openjdk-8-jdk \
    libapr1-dev \
    libcurl4-openssl-dev \
    libsvn-dev \
    libssl-dev \
    libsasl2-dev \
    libtool \
    python-dev && \
  apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh"]
